[package]
name = "stickman"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "stickman"
path = "src/bin/main.rs"

[dependencies]
twowaiyo = { path =  "../twowaiyo" }
async-std = { version = "^1.5.0" }
