name: gh.build-and-test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: cargo build
      - name: test
        run: cargo test
