name: gh.build-and-test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: cargo build
      - name: test
        run: cargo test
  dist:
    runs-on: ubuntu-latest
    container:
      image: rust:1.57.0
    steps:
      - uses: actions/checkout@v2
      - name: Update apt
        run: apt-get update
      - name: Install packages
        run: apt-get install -y libssl-dev postgresql-client libpq-dev gcc-arm-linux-gnueabihf nodejs npm
      - name: Download openssl
        run: cd /tmp && wget https://www.openssl.org/source/openssl-1.1.1g.tar.gz
      - name: Extract openssl
        run: cd /tmp && tar xzf openssl-1.1.1g.tar.gz
      - name: Configure openssl
        run: cd /tmp/openssl-1.1.1g && ./config shared
        env:
          MACHINE: armv7
          ARCH: arm
          CC: arm-linux-gnueabihf-gcc
      - name: Build openssl
        run: cd /tmp/openssl-1.1.1g && make
        env:
          MACHINE: armv7
          ARCH: arm
          CC: arm-linux-gnueabihf-gcc
      - name: Add target
        run: rustup target add armv7-unknown-linux-gnueabihf
      - name: Add target components
        run: rustup component add --target armv7-unknown-linux-gnueabihf rust-src rust-std rustc-dev
      - name: Build w/ target
        run: cargo build --target armv7-unknown-linux-gnueabihf --release
        env:
          OPENSSL_LIB_DIR: /tmp/openssl-1.1.1g/
          OPENSSL_INCLUDE_DIR: /tmp/openssl-1.1.1g/include
      - name: Prepare distributable directory
        run: mkdir -p target/dist/twowaiyo
      - name: Populate distributable (twowaiyo)
        run: cp target/armv7-unknown-linux-gnueabihf/release/twowaiyo target/dist/twowaiyo/twowaiyo
      - name: Populate distributable (stickbot)
        run: cp target/armv7-unknown-linux-gnueabihf/release/stickbot target/dist/twowaiyo/stickbot
      - name: Populate distributable (boxbot)
        run: cp target/armv7-unknown-linux-gnueabihf/release/boxbot target/dist/twowaiyo/boxbot
      - name: Compress distributable
        run: tar cvzf ./twowaiyo-armv7-unknown-linux-gnueabihf.tar.gz -C target/dist twowaiyo
